[package]
name = "projekt"
version = "0.1.0"
authors = ["Kmirek3110 <chemionpl@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

chrono = "*"
grabinput = "0.1.1"
csv = "1.1"
linreg = "*"

